# Generated by Django 3.1.3 on 2020-11-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('test_round', models.IntegerField(default=0)),
                ('register_day_start', models.DateField()),
                ('register_day_end', models.DateField()),
                ('test_day', models.DateTimeField()),
                ('results_day', models.DateTimeField()),
                ('test_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
