# Generated by Django 3.1.3 on 2020-11-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
